hospital_management_system/Payment/urls.py
from django.contrib import admin
from django.urls import path
from Payment import views
from django.conf.urls import url

app_name = "Payment"

urlpatterns = [
    url('prescription_list/', views.prescription_list, name="Prescription_List"),
    url('view_bill/', views.view_bill, name="Bill Details"),
    url(r'^bill/(?P<id>\d+)/', views.view_bill_for_patient, name='Bill_Details_for_Patient'),
    url(r'^prescription/new/$', views.add_new_prescription, name='New Prescription'),
    url(r'^bill/new/$', views.add_new_bill, name='New_Bill'),
    url(r'^medicine/(?P<id>\d+)/', views.view_medicine, name='View_Medicine'),
    url(r'^patient/$', views.patient_name, name='View_Bill'),
]

hospital_management_system/Person/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include,url
from . import views
from Person.models import Persons, Patient, Employee, Doctors
app_name='person'
urlpatterns=[
	url(r'^patients/$',views.listPatients, name='patient_list'),
	url(r'^doctors/$',views.listDoctors, name='doctor_list'),
	url(r'^nurses/$',views.listNurses, name='nurse_list'),
	url(r'^staff/$', views.listStaff, name='staff_list'),
    url(r'^enter_details/patient/$', views.postPatients, name='patient_details'),
	url(r'^enter_details/doctor/$', views.postDoctors, name='doctor_details'),
	url(r'^enter_details/nurse/$', views.postNurse, name='nurse_details'),
	url(r'^update_details/patients/(?P<id>\d+)$', views.UpdatePatient, name='update_patient'),
	url(r'^update_details/doctors/(?P<id>\d+)$', views.updateDoc, name='update_Doctor'),
	url(r'^update_details/nurses/(?P<id>\d+)$', views.updateNurse, name='update_nurse'),
]

hospital_management_system/accounts/urls.py
from django.urls import path
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'
urlpatterns = [
    path(r'^signup/$', views.signup, name='signup'),
    url(r'^login/$', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
]

hospital_management_system/hospital/urls.py
from django.conf.urls import url
from . import views

app_name = 'hospital'
urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^rooms/$', views.rooms_list, name='rooms'),
    url(r'^rooms/patient/details/(?P<id>\d+)$', views.patient_room_details, name='rooms_patient_details'),
    url(r'^rooms/surgery/details/(?P<id>\d+)$', views.surgery_room_details, name='rooms_surgery_details'),
    url(r'^post/room/patient/$', views.post_patient_room, name='post_patient_room'),
    url(r'^post/room/surgery/$', views.post_surgery_room, name='post_surgery_room'),
    url(r'^post/hospital/$', views.post_hospital, name='post_hospital'),
    url(r'^check_in/patient/(?P<id>\d+)$', views.check_patient_in_room, name='patient_check_in'),
    url(r'^check_out/patient/(?P<id>\d+)$', views.check_patient_out_room, name='patient_check_out'),
    url(r'^book/surgery/(?P<id>\d+)$', views.book_surgery_room, name='book_surgery'),
    url(r'^check_out/surgery/(?P<id>\d+)$', views.checkout_surgery_room, name='check_out_surgery'),
    url(r'^schedule/$', views.display_surgery_schedule, name='surgery_schedule'),
]

hospital_management_system/hospital_management_system/urls.py
from django.urls import path
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts', include('accounts.urls')),
    path('', include('hospital.urls')),
    path('payment/', include('Payment.urls')),
    path('surgery_details/', include('Surgery_Details.urls')),
    path('', include('Person.urls')),
    path('', include('Payment.urls')),
    path('', include('Surgery_Details.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

hospital_management_system/Person/models.py
from django.db import models
from decimal import Decimal
# Create your models here.


# Create your models here.

class Persons(models.Model):

    firstName = models.CharField(max_length=200)
    lastName = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    phoneNumber = models.CharField(max_length=200)
    social = models.CharField(max_length=200)

    def __str__(self):
        return self.firstName+ " "+ self.lastName

    class Meta:
        abstract = True


class Employee(Persons):
    shift = models.CharField(max_length=200, default='', blank=True)
    jobDesc = models.CharField(max_length=200, default='', blank=True)
    salary = models.DecimalField(max_digits=7, decimal_places=0, default=Decimal('0.00'))

    class Meta:
        abstract=True


class Doctors(Employee):
    specialty = models.CharField(max_length=200, default='', blank=True)
    # surgeries = models.ManyToManyField(Surgery, symmetrical=False, null=True)
    # surgery=models.ForeignKey() #total number of surgeries for particular doctor


class Nurses(Employee):
    specialty = models.CharField(max_length=200, default='', blank=True)
    # patient_rooms = models.ManyToManyField(PatientRoom, symmetrical=False, null=True)


class Patient(Persons):
    symptoms = models.CharField(max_length=200, default='', blank=True)
    allergies = models.CharField(max_length=200, default='', blank=True)
    currentMeds = models.CharField(max_length=200, default='', blank=True)
    docName = models.ForeignKey(Doctors, on_delete=models.CASCADE, default='1')

hospital_management_system/Person/forms.py
from django import forms
from Person.models import Doctors, Nurses, Patient

class addPatient(forms.ModelForm):
    class Meta:
        model=Patient
        fields=['firstName', 'lastName','address','phoneNumber', 'social']
    
class addNurses(forms.ModelForm):
    class Meta:
        model=Nurses
        fields=['firstName', 'lastName','address','phoneNumber','social']

class addDoctors(forms.ModelForm):
    class Meta:
        model=Doctors
        fields=['firstName', 'lastName','address','phoneNumber','social']


class UpdatePatientDetails(forms.ModelForm):
    class Meta:
        model= Patient
        fields=['symptoms','allergies','currentMeds','docName']

class UpdateDoctors(forms.ModelForm):
    class Meta:
        model=Doctors
        fields=['shift', 'jobDesc', 'salary', 'specialty']
class UpdateNurses(forms.ModelForm):
    class Meta:
        model=Nurses
        fields=['shift', 'jobDesc', 'salary'] 

hospital_management_system/Person/views.py
from django.shortcuts import render, get_object_or_404, redirect
from Person.models import Persons, Patient, Employee, Doctors, Nurses
from hospital.models import Hospital, PatientRoom, SurgeryRoom
from .forms import addPatient, addNurses, addDoctors, UpdatePatientDetails, UpdateDoctors, UpdateNurses
# Create your views here.



def listPatients(request):
	hospital=get_object_or_404(Hospital, id=1)
	patientList=hospital.patients.all()
	print(patientList)
	return render(request, 'listpatients.html', {'patientList':patientList, 'hospital':hospital})


def postPatients(request):
	hospital=get_object_or_404(Hospital, id=1)
	form=addPatient(request.POST)
	if form.is_valid():
		item=form.save(commit=False)
		item.save()
		hospital.patients.add(item)
		return redirect('hospital:home')
	else:
		form=addPatient()
		return render(request, 'post_element.html', {'form':form, 'button_title':'Add Patient', 'hospital':hospital})

def UpdatePatient(request, id):
	hospital=get_object_or_404(Hospital, id=1)
	instance=get_object_or_404(Patient, id=id)
	form=UpdatePatientDetails(request.POST, instance=instance)
	if form.is_valid():
		item=form.save(commit=False)
		item.save()
		hospital.patients.add(item)
		return redirect('hospital:home')
	else:
		form=UpdatePatientDetails()
		return render(request, 'post_element.html', {'form':form, 'button_title':'Add Patient', 'hospital':hospital})



def listDoctors(request):
	hospital=get_object_or_404(Hospital, id=1)
	docList=hospital.doctors.all()
	print(docList)
	return render(request, 'listdoctors.html', {'docList':docList, 'hospital':hospital})
 

def postDoctors(request):	
	hospital=get_object_or_404(Hospital, id=1)
	form=addDoctors(request.POST)
	if form.is_valid():
		item=form.save(commit=False)
		item.save()
		hospital.doctors.add(item)
		return redirect('hospital:home')
	else:
		form=addDoctors()
		return render(request, 'post_element.html', {'form':form, 'button_title':'Add Doctors', 'hospital':hospital})


def updateDoc(request, id):
	hospital=get_object_or_404(Hospital, id=1)
	instance=get_object_or_404(Doctors, id=id)
	form=UpdateDoctors(request.POST, instance=instance)
	if form.is_valid():
		item=form.save(commit=False)
		item.save()
		hospital.doctors.add(item)
		return redirect('person:staff_list')
	else:
		form=UpdateDoctors()
		return render(request, 'post_element.html', {'form':form, 'button_title':'Add Doctors', 'hospital':hospital})


def listNurses(request):
	hospital=get_object_or_404(Hospital, id=1)
	nurseList=hospital.nurses.all()
	print(nurseList)
	return render(request, 'listnurses.html', {'nurseList':nurseList, 'hospital':hospital})
def postNurse(request):
	hospital=get_object_or_404(Hospital, id =1)
	form=addNurses(request.POST)
	if form.is_valid():
		item=form.save(commit=False)
		item.save()
		hospital.nurses.add(item)
		return redirect('hospital:home')
	else:
		form=addNurses()
		return render(request, 'post_element.html', {'form':form, 'button_title':'Add Nurses', 'hospital':hospital})

def updateNurse(request, id):
	hospital=get_object_or_404(Hospital, id=1)
	instance=get_object_or_404(Nurses, id=id)	

	form=UpdateNurses(request.POST,instance=instance)
	if form.is_valid():
		item=form.save(commit=False)
		item.save()
		hospital.nurses.add(item)
		return redirect('person:staff_list')
	else:
		form=UpdateNurses()
		return render(request, 'post_element.html', {'form':form, 'button_title':'Add Nurses', 'hospital':hospital})

def listStaff(request):
	hospital=get_object_or_404(Hospital, id=1)
	nursesList=hospital.nurses.all()
	doctorsList=hospital.doctors.all()
	print(doctorsList)
	print(nursesList)
	return render(request, 'Staff.html',{'doctorsList':doctorsList, 'nursesList':nursesList, 'hospital':hospital})

hospital_management_system/Person/templates/Staff.html
{% extends "base.html" %}

{% block header %}
<div class="container_header">
    {% if hospital is not None %}
        <div class="container_hospital_info">
            <div class="hospital_title"><a class="hospital_title_text" href="{% url 'hospital:home' %}">{{ hospital.name }}</a></div>
            <div class="hospital_info">
                <div>{{ hospital.address }}</div>
                <div class="padding"></div>
                <div>{{ hospital.phone_number }}</div>
            </div>
        </div>
    {% else %}
        <a href="/" class="logo">My Hospital</a>
    {% endif %}

    <div class="container_user_info">
        {% if user.is_authenticated %}
            <div class="user_name_info">Hello, {{user.username}}</div>
            <div><a class="log_out" href="{% url 'accounts:logout' %}">Log out</a></div>
        {% else %}
            <a href="{% url 'accounts:login' %}">Log in</a>
        {% endif %}
    </div>
</div>
{% endblock %}

{% block content %}
    <div class="container_doctor"> 
        <h2 class="Doctor List">Doctor List</h2>
        <table>
            <tr>
                <th class="doctor_name_table_header">Doctor Name</th>
                <th class="doctor_specialty_table_header">Specialty</th>
            </tr>
        
    
        {%for dr in doctorsList%} 
            <tr class="table_row_doctor">
                <td>Dr.{{dr.firstName}} {{dr.lastName}} </td>
                <td>{{dr.specialty}}</td>
                
            </tr>
        {%endfor%}
        </table>
    </div>

    <div class="container_nurse"></div>
        <h2 class="Nurse  List">Nurse List</h2>
        
        <table>
            <tr>
                <th class="nurse_name_table_header">Nurse Name</th>
                <th class="nurse_shift_table_header">Shift</th>
            </tr>
                
        {%for nr in nursesList%} 
                <tr class="table_row_nurse">
                    <td>{{nr.firstName}} {{nr.lastName}}</td>
                    <td>{{nr.shift}}</td>
                </tr>
        {%endfor%}
        </table>
    </div>
{% endblock %}

hospital_management_system/Person/templates/listdoctors.html
{% extends "base.html" %}

{% block header %}
<div class="container_header">
    {% if hospital is not None %}
        <div class="container_hospital_info">
            <div class="hospital_title"><a class="hospital_title_text" href="{% url 'hospital:home' %}">{{ hospital.name }}</a></div>
            <div class="hospital_info">
                <div>{{ hospital.address }}</div>
                <div class="padding"></div>
                <div>{{ hospital.phone_number }}</div>
            </div>
        </div>
    {% else %}
        <a href="/" class="logo">My Hospital</a>
    {% endif %}

    <div class="container_user_info">
        {% if user.is_authenticated %}
            <div class="user_name_info">Hello, {{user.username}}</div>
            <div><a class="log_out" href="{% url 'accounts:logout' %}">Log out</a></div>
        {% else %}
            <a href="{% url 'accounts:login' %}">Log in</a>
        {% endif %}
    </div>
</div>
{% endblock %}


{% block content %}
    <div class="container_doctor">     
    <h2 class="Doctor List">Doctor List</h2>
        <table>
            <tr>
                <th class="doctorname_table_header">Our Doctors</th>
            </tr>
        {%for dr in docList%} 
            <tr class="table_row_doctor">
                <td>Dr.{{dr.firstName}} {{dr.lastName}}</td>
            </tr>
        {%endfor%}
        </table>
    </div>
{% endblock %}

hospital_management_system/Person/templates/listnurses.html
{% extends "base.html" %}

{% block header %}
<div class="container_header">
    {% if hospital is not None %}
        <div class="container_hospital_info">
            <div class="hospital_title"><a class="hospital_title_text" href="{% url 'hospital:home' %}">{{ hospital.name }}</a></div>
            <div class="hospital_info">
                <div>{{ hospital.address }}</div>
                <div class="padding"></div>
                <div>{{ hospital.phone_number }}</div>
            </div>
        </div>
    {% else %}
        <a href="/" class="logo">My Hospital</a>
    {% endif %}

    <div class="container_user_info">
        {% if user.is_authenticated %}
            <div class="user_name_info">Hello, {{user.username}}</div>
            <div><a class="log_out" href="{% url 'accounts:logout' %}">Log out</a></div>
        {% else %}
            <a href="{% url 'accounts:login' %}">Log in</a>
        {% endif %}
    </div>
</div>
{% endblock %}


{% block content %}
    <div class="container_nurse"> 
        <h2 class="Nurse  List">Nurse List</h2>
        <table>
            <tr>
                <th class="nurse_name_table_header">Nurses</th>
            </tr>
            {%for nr in nurseList%} 
                <tr class="table_row_nurse">
                    <td>{{nr.firstName}} {{nr.lastName}}</td>
                </tr>
            {%endfor%}
        </table>    
    </div>x

{% endblock %}

hospital_management_system/Person/templates/listpatients.html
{% extends "base.html" %}

{% block header %}
<div class="container_header">
    {% if hospital is not None %}
        <div class="container_hospital_info">
            <div class="hospital_title"><a class="hospital_title_text" href="{% url 'hospital:home' %}">{{ hospital.name }}</a></div>
            <div class="hospital_info">
                <div>{{ hospital.address }}</div>
                <div class="padding"></div>
                <div>{{ hospital.phone_number }}</div>
            </div>
        </div>
    {% else %}
        <a href="/" class="logo">My Hospital</a>
    {% endif %}

    <div class="container_user_info">
        {% if user.is_authenticated %}
            <div class="user_name_info">Hello, {{user.username}}</div>
            <div><a class="log_out" href="{% url 'accounts:logout' %}">Log out</a></div>
        {% else %}
            <a href="{% url 'accounts:login' %}">Log in</a>
        {% endif %}
    </div>
</div>
{% endblock %}


{% block content %}    
    <div class="container_patient"> 
        <h2 class="Patient List">Patient List</h2>
        <table>
            <tr>
                <th class="patient_name_table_header">Patient Name</th>
                <th class="patient_symptoms_table_header">Symptoms</th>
                <th class="patient_currentMeds_table_header">Current Medications</th>
                <th class="patient_docName_table_header">Patient Doctor</th>
                <th class="patient_bill_details_table_header">Bill</th>
            </tr>
            {%for pr in patientList%} 
                <tr class="table_row_patient">
                    <td>{{pr.lastName}}, {{pr.firstName}}</td>
                    <td>{{pr.symptoms}}</td>
                    <td>{{pr.docName}}</td>
                    <td>{{pr.currentMeds}}</td>
                    <td><a href="{% url 'Payment:Bill_Details_for_Patient' pr.id %}">Click Here</a></td>
                </tr>
            {%endfor%}
        </table>
    </div>


{% endblock %}

hospital_management_system/Person/templates/post_element.html
{% extends "hospital/base.html" %}

{% block content %}
    <h2 class="title_element">{{ button_title }}</h2>
	<form method='post' class='add_item'>
		{% csrf_token %}
		{{ form.as_p }}
		<button type='submit'>{{button_title}}</button>
	</form>
{% endblock %}