hospital_management_system/Payment/urls.py
from django.contrib import admin
from django.urls import path
from Payment import views
from django.conf.urls import url

app_name = "Payment"

urlpatterns = [
    url('prescription_list/', views.prescription_list, name="Prescription_List"),
    url('view_bill/', views.view_bill, name="Bill Details"),
    url(r'^bill/(?P<id>\d+)/', views.view_bill_for_patient, name='Bill_Details_for_Patient'),
    url(r'^prescription/new/$', views.add_new_prescription, name='New Prescription'),
    url(r'^bill/new/$', views.add_new_bill, name='New_Bill'),
    url(r'^medicine/(?P<id>\d+)/', views.view_medicine, name='View_Medicine'),
    url(r'^patient/$', views.patient_name, name='View_Bill'),
]

hospital_management_system/Person/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include,url
from . import views
from Person.models import Persons, Patient, Employee, Doctors
app_name='person'
urlpatterns=[
	url(r'^patients/$',views.listPatients, name='patient_list'),
	url(r'^doctors/$',views.listDoctors, name='doctor_list'),
	url(r'^nurses/$',views.listNurses, name='nurse_list'),
	url(r'^staff/$', views.listStaff, name='staff_list'),
    url(r'^enter_details/patient/$', views.postPatients, name='patient_details'),
	url(r'^enter_details/doctor/$', views.postDoctors, name='doctor_details'),
	url(r'^enter_details/nurse/$', views.postNurse, name='nurse_details'),
	url(r'^update_details/patients/(?P<id>\d+)$', views.UpdatePatient, name='update_patient'),
	url(r'^update_details/doctors/(?P<id>\d+)$', views.updateDoc, name='update_Doctor'),
	url(r'^update_details/nurses/(?P<id>\d+)$', views.updateNurse, name='update_nurse'),
]

hospital_management_system/Surgery_Details/urls.py
from Surgery_Details import views
from django.conf.urls import url

app_name = "Surgery_Details"

urlpatterns = [
    url('surgery_list/', views.view_surgery_details, name="Surgery_List"),
    url('equipment_details/', views.view_equipment_details, name="Equipment_Details"),
    url(r'^surgery/new/$', views.add_new_surgery_details, name='New_Surgery'),
    url(r'^equipment/new/$', views.add_new_equipment, name='New_Equipment'),
    url(r'^surgery/(?P<id>\d+)/', views.view_surgery, name='Surgery'),
    url(r'^equipment/(?P<id>\d+)/', views.view_equipment, name='Equipment'),
]

hospital_management_system/accounts/urls.py
from django.urls import path
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'
urlpatterns = [
    path(r'^signup/$', views.signup, name='signup'),
    url(r'^login/$', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
]

hospital_management_system/hospital/urls.py
from django.conf.urls import url
from . import views

app_name = 'hospital'
urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^rooms/$', views.rooms_list, name='rooms'),
    url(r'^rooms/patient/details/(?P<id>\d+)$', views.patient_room_details, name='rooms_patient_details'),
    url(r'^rooms/surgery/details/(?P<id>\d+)$', views.surgery_room_details, name='rooms_surgery_details'),
    url(r'^post/room/patient/$', views.post_patient_room, name='post_patient_room'),
    url(r'^post/room/surgery/$', views.post_surgery_room, name='post_surgery_room'),
    url(r'^post/hospital/$', views.post_hospital, name='post_hospital'),
    url(r'^check_in/patient/(?P<id>\d+)$', views.check_patient_in_room, name='patient_check_in'),
    url(r'^check_out/patient/(?P<id>\d+)$', views.check_patient_out_room, name='patient_check_out'),
    url(r'^book/surgery/(?P<id>\d+)$', views.book_surgery_room, name='book_surgery'),
    url(r'^check_out/surgery/(?P<id>\d+)$', views.checkout_surgery_room, name='check_out_surgery'),
    url(r'^schedule/$', views.display_surgery_schedule, name='surgery_schedule'),
]

hospital_management_system/hospital_management_system/urls.py
from django.urls import path
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts', include('accounts.urls')),
    path('', include('hospital.urls')),
    path('payment/', include('Payment.urls')),
    path('surgery_details/', include('Surgery_Details.urls')),
    path('', include('Person.urls')),
    path('', include('Payment.urls')),
    path('', include('Surgery_Details.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

hospital_management_system/hospital/models.py
from django.db import models
from Person.models import Doctors, Nurses, Patient
from Surgery_Details.models import Surgery, Equipment


class Room(models.Model):
    room_number = models.BigIntegerField(unique=True)
    is_occupied = models.BooleanField(default='0')

    def __str__(self):
        return str(self.room_number)

    class Meta:
        abstract = True


class PatientRoom(Room):
    price = models.DecimalField(default=0.0, decimal_places=2, max_digits=100)
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, related_name='patient', null=True)
    nurse = models.ForeignKey(Nurses, on_delete=models.CASCADE, related_name='nurse', null=True)

class SurgeryRoom(Room):
    equipment = models.ManyToManyField(Equipment, blank=True, null=True)
    surgery = models.ForeignKey(Surgery, on_delete=models.CASCADE, related_name='surgery', null=True)


# Create your models here.
class Hospital(models.Model):
    name = models.CharField(max_length=50)
    address = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=10)
    patient_rooms = models.ManyToManyField(PatientRoom, symmetrical=False)
    surgery_rooms = models.ManyToManyField(SurgeryRoom, symmetrical=False)
    patients = models.ManyToManyField(Patient, symmetrical=False)
    doctors = models.ManyToManyField(Doctors, symmetrical=False)
    nurses = models.ManyToManyField(Nurses, symmetrical=False)

    def save(self, *args, **kwargs):
        if Hospital.objects.count() >= 1:
            raise PermissionError("Only one Hospital is allowed")

        super(Hospital, self).save(*args, **kwargs)

hospital_management_system/hospital/forms.py
from django import forms
from .models import PatientRoom, SurgeryRoom, Hospital
from Surgery_Details.models import Equipment


class PostPatientRoom(forms.ModelForm):
    class Meta:
        model = PatientRoom
        fields = ['room_number', 'price']


class PostSurgeryRooom(forms.ModelForm):
    class Meta:
        model = SurgeryRoom
        exclude = ['is_occupied', 'surgery']

    def __init__(self, *args, **kwargs):
        super(PostSurgeryRooom, self).__init__(*args, **kwargs)
        self.fields['equipment'].widget = forms.widgets.CheckboxSelectMultiple()
        self.fields['equipment'].help_text = ""
        self.fields['equipment'].queryset = Equipment.objects.all()


class PostHospital(forms.ModelForm):
    class Meta:
        model = Hospital
        fields = ['name', 'address', 'phone_number']


class UpdatePatientRoom(forms.ModelForm):
    class Meta:
        model = PatientRoom
        fields = ['patient', 'nurse']


class UpdateSurgeryRoom(forms.ModelForm):
    class Meta:
        model = SurgeryRoom
        fields = ['surgery']

hospital_management_system/hospital/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Hospital, PatientRoom, SurgeryRoom
from .forms import PostPatientRoom, PostHospital, PostSurgeryRooom, UpdatePatientRoom, UpdateSurgeryRoom
from datetime import datetime


# Create your views here.
def home(request):
    try:
        hospital = Hospital.objects.filter(id=1)[0]
    except IndexError:
        hospital = None
    return render(request, 'hospital/home.html', {'hospital': hospital})


def rooms_list(request):
    hospital = get_object_or_404(Hospital, id=1)
    patient_rooms = hospital.patient_rooms.all()
    surgery_rooms = hospital.surgery_rooms.all()
    return render(request, 'hospital/list_all_rooms.html',
                  {'surgery_rooms': surgery_rooms, 'patient_rooms': patient_rooms, 'hospital': hospital})


def patient_room_details(request, id):
    instance = get_object_or_404(PatientRoom, id=id)
    return render(request, 'hospital/room_details.html', {'room': instance})


def surgery_room_details(request, id):
    instance = get_object_or_404(SurgeryRoom, id=id)
    return render(request, 'hospital/room_details.html', {'room': instance})


def post_hospital(request):
    if request.method == 'POST':
        form = PostHospital(request.POST)
        if form.is_valid():
            item = form.save(commit=False)
            item.save()
            return redirect('hospital:rooms')
    else:
        form = PostHospital()
    return render(request, 'hospital\post_element.html', {'form': form, 'button_title': 'Post Hospital'})


def post_patient_room(request):
    hospital = get_object_or_404(Hospital, id=1)
    if request.method == 'POST':
        form = PostPatientRoom(request.POST)
        if form.is_valid():
            item = form.save(commit=False)
            item.save()
            hospital.patient_rooms.add(item)
            return redirect('hospital:rooms')
    else:
        form = PostPatientRoom()
    return render(request, 'hospital\post_element.html', {'form': form, 'button_title': 'Post Patient Room'})


def post_surgery_room(request):
    hospital = get_object_or_404(Hospital, id=1)
    if request.method == 'POST':
        form = PostSurgeryRooom(request.POST)
        if form.is_valid():
            item = form.save(commit=False)
            item.save()
            hospital.surgery_rooms.add(item)
            return redirect('hospital:rooms')
    else:
        form = PostSurgeryRooom()
    return render(request, 'hospital\post_element.html', {'form': form, 'button_title': 'Post Surgery Room'})


def check_patient_in_room(request, id):
    instance = get_object_or_404(PatientRoom, id=id)
    form = UpdatePatientRoom(request.POST, instance=instance)
    if form.is_valid():
        item = form.save(commit=False)
        item.is_occupied = '1'
        item.save()
        return redirect('hospital:rooms')
    else:
        form = UpdatePatientRoom()
    return render(request, 'hospital\post_element.html', {'form': form, 'button_title': 'Check Patient In'})


def check_patient_out_room(request, id):
    instance = get_object_or_404(PatientRoom, id=id)
    instance.is_occupied = '0'
    instance.nurse_id = None
    instance.patient_id = None
    instance.save()
    return redirect('hospital:rooms')


def book_surgery_room(request, id):
    instance = get_object_or_404(SurgeryRoom, id=id)
    form = UpdateSurgeryRoom(request.POST, instance=instance)
    if form.is_valid():
        item = form.save(commit=False)
        item.is_occupied = '1'
        item.save()
        return redirect('hospital:rooms')
    else:
        form = UpdateSurgeryRoom()
    return render(request, 'hospital\post_element.html', {'form': form, 'button_title': 'Book Surgery Room'})


def checkout_surgery_room(request, id):
    instance = get_object_or_404(SurgeryRoom, id=id)
    instance.is_occupied = '0'
    instance.surgery_id = None
    instance.save()
    return redirect('hospital:rooms')


def display_surgery_schedule(request):
    hospital = get_object_or_404(Hospital, id=1)
    datetime_now = datetime.now()
    surgery_rooms_booked = hospital.surgery_rooms.all().filter(is_occupied='1').order_by('surgery__start_time')
    surgery_rooms_free = hospital.surgery_rooms.all().filter(is_occupied='0').order_by('surgery__start_time')
    return render(request, 'hospital\surgery_schedule.html', {'booked': surgery_rooms_booked,
                                                              'free': surgery_rooms_free,
                                                              'time': datetime_now,
                                                              'hospital': hospital})

hospital_management_system/hospital/templates/hospital/home.html
{% extends "hospital/base.html" %}

{% block header %}
    <div class="container_header">
        {% if hospital is not None %}
            <div class="container_hospital_info">
                <div class="hospital_title"><a class="hospital_title_text" href="{% url 'hospital:home' %}">{{ hospital.name }}</a></div>
                <div class="hospital_info">
                    <div>{{ hospital.address }}</div>
                    <div class="padding"></div>
                    <div>{{ hospital.phone_number }}</div>
                </div>
            </div>
        {% else %}
            <a href="/" class="logo">My Hospital</a>
        {% endif %}

        <div class="container_user_info">
            {% if user.is_authenticated %}
                <div class="user_name_info">Hello, {{user.username}}</div>
                <div><a class="log_out" href="{% url 'accounts:logout' %}">Log out</a></div>
            {% else %}
                <a href="{% url 'accounts:login' %}">Log in</a>
            {% endif %}
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="menu_items">
        {% if not hospital is None %}
            <div class="container_main_menu">
                <h2 class="title_main_menu">Welcome to {{ hospital.name }}</h2>
                {% if user.is_authenticated %}
                    <div class="home_list_container">
                        <div class="home_list_item_container">
                            <div class="home_list_item"><a class="home_list_item_text" href="{%url 'person:patient_details' %}">Patient Registration</a></div>
                            <div class="home_list_item_image" id="home_list_item_registration"></div>
                        </div>

                        <div class="home_list_item_container">
                            <div class="home_list_item"><a class="home_list_item_text" href="{%url 'person:staff_list' %}">Our Staff</a></div>
                            <div class="home_list_item_image" id="home_list_item_staff"></div>
                        </div>

                        <div class="home_list_item_container">
                            <div class="home_list_item"><a class="home_list_item_text" href="{% url 'hospital:surgery_schedule' %}">Surgeries Schedule</a></div>
                            <div class="home_list_item_image" id="home_list_item_surgery"></div>
                        </div>

                        <div class="home_list_item_container">
                            <div class="home_list_item"><a class="home_list_item_text" href="{% url 'hospital:rooms' %}">Rooms</a></div>
                            <div class="home_list_item_image" id="home_list_item_rooms"></div>
                        </div>

                        <div class="home_list_item_container">
                            <div class="home_list_item"><a class="home_list_item_text" href="{% url 'person:patient_list' %}">Billing</a></div>
                            <div class="home_list_item_image" id="home_list_item_bill"></div>
                        </div>
                        <div class="home_list_item_container">
                                <div class="home_list_item"><a class="home_list_item_text" href="{% url 'hospital:post_patient_room' %}">Create a Patient Room</a></div>
                            </div>
                        <div class="home_list_item_container">
                            <div class="home_list_item"><a class="home_list_item_text" href="{% url 'hospital:post_surgery_room' %}">Create a Surgery Room</a></div>
                        </div>
                        <div class="home_list_item_container">
                            <div class="home_list_item"><a class="home_list_item_text" href="{% url 'person:doctor_details' %}">Doctor Registration</a></div>
                        </div>

                        <div class="home_list_item_container">
                            <div class="home_list_item"><a class="home_list_item_text" href="{% url 'person:nurse_details' %}">Nurse Registration</a></div>
                        </div>
                        <div class="home_list_item_container">
                            <div class="home_list_item"><a class="home_list_item_text" href="{% url 'Surgery_Details:New_Equipment' %}">Add Equipment</a></div>
                        </div>
                        <div class="home_list_item_container">
                            <div class="home_list_item"><a class="home_list_item_text" href="{% url 'Surgery_Details:New_Surgery' %}">Add Surgery</a></div>
                        </div>
                        <div class="home_list_item_container">
                            <div class="home_list_item"><a class="home_list_item_text" href="{% url 'Surgery_Details:Surgery_List' %}">List All Surgery</a></div>
                        </div>
                        <div class="home_list_item_container">
                            <div class="home_list_item"><a class="home_list_item_text" href="{% url 'Surgery_Details:Equipment_Details' %}">List All Equipments</a></div>
                        </div>
                        <div class="home_list_item_container">
                            <div class="home_list_item"><a class="home_list_item_text" href="{% url 'Payment:Prescription_List' %}">Medicine Stock List</a></div>
                        </div>
                        <div class="home_list_item_container">
                            <div class="home_list_item"><a class="home_list_item_text" href="{% url 'Payment:New_Bill' %}">Generate Bill</a></div>
                        </div>
                    </div>
                {% else %}
                <div class="home_list_container">
                    <div class="home_list_item_container">
                        <div class="home_list_item"><a class="home_list_item_text" href="{%url 'person:patient_details' %}">Patient Registration</a></div>
                        <div class="home_list_item_image" id="home_list_item_registration"></div>
                    </div>

                    <div class="home_list_item_container">
                        <div class="home_list_item"><a class="home_list_item_text" href="{%url 'person:staff_list' %}">Our Staff</a></div>
                        <div class="home_list_item_image" id="home_list_item_staff"></div>
                    </div>

                    <div class="home_list_item_container">
                        <div class="home_list_item"><a class="home_list_item_text" href="{% url 'hospital:surgery_schedule' %}">Surgeries Schedule</a></div>
                        <div class="home_list_item_image" id="home_list_item_surgery"></div>
                    </div>

                    <div class="home_list_item_container">
                        <div class="home_list_item"><a class="home_list_item_text" href="{% url 'hospital:rooms' %}">Rooms</a></div>
                        <div class="home_list_item_image" id="home_list_item_rooms"></div>
                    </div>

                    <div class="home_list_item_container">
                        <div class="home_list_item"><a class="home_list_item_text" href="{% url 'person:patient_list' %}">Billing</a></div>
                        <div class="home_list_item_image" id="home_list_item_bill"></div>
                    </div>
                </div>
                {%endif%}    
            </div>
        {% else %}
            <p>Your hospital has not been created yet</p>
            <a href="{% url 'hospital:post_hospital' %}">Click here to create one!</a>
        {% endif %}
    </div>
{% endblock %}

hospital_management_system/hospital/templates/hospital/list_all_rooms.html
{% extends "hospital/base.html" %}

{% block header %}
    <div class="container_header">
        {% if hospital is not None %}
            <div class="container_hospital_info">
                <div class="hospital_title"><a class="hospital_title_text" href="{% url 'hospital:home' %}">{{ hospital.name }}</a></div>
                <div class="hospital_info">
                    <div>{{ hospital.address }}</div>
                    <div class="padding"></div>
                    <div>{{ hospital.phone_number }}</div>
                </div>
            </div>
        {% else %}
            <a href="/" class="logo">My Hospital</a>
        {% endif %}

        <div class="container_user_info">
            {% if user.is_authenticated %}
                <div class="user_name_info">Hello, {{user.username}}</div>
                <div><a class="log_out" href="{% url 'accounts:logout' %}">Log out</a></div>
            {% else %}
                <a href="{% url 'accounts:login' %}">Log in</a>
            {% endif %}
        </div>
    </div>
{% endblock %}

{% block content %}
    <h2 class="title_rooms">Surgery Rooms</h2>
        <table>
            <tr>
                <th class="room_number_table_header">Room Number</th>
                <th class="patient_name_table_header">Patient</th>
                <th>Doctor</th>
                <th class="check_inout_table_header">Book/Checkout</th>
                <th class="room_details_table_header">Details</th>
                <th>Available</th>
            </tr>
        {% for sr in surgery_rooms %}
            <tr class="table_surgery_room">
                <td>{{sr.room_number}}</td>
                {% if not sr.is_occupied %}
                    <td>N/A</td>
                    <td>N/A</td>
                    <td><a href="{% url 'hospital:book_surgery' sr.id %}">Book Surgery</a></td>
                    <td><a href="{% url 'hospital:rooms_surgery_details' sr.id %}">Details</a></td>
                    <td class="table_row_available"></td>
                {% else %}
                    <td>{{sr.surgery.patient.lastName}}, {{sr.surgery.patient.firstName}}</td>
                    <td>{{sr.surgery.doctor_incharge.lastName}}, {{sr.surgery.doctor_incharge.firstName}}</td>
                    <td><a href="{% url 'hospital:check_out_surgery' sr.id %}">Check out</a></td>
                    <td><a href="{% url 'hospital:rooms_surgery_details' sr.id %}">Details</a></td>
                    <td class="table_row_not_available"></td>
                {% endif %}
            </tr>
        {% endfor %}
        </table>

    <h2 class="title_rooms">Patient Rooms</h2>
        <table>
            <tr>
                <th class="room_number_table_header">Room Number</th>
                <th class="patient_name_table_header">Patient</th>
                <th>Nurse</th>
                <th class="check_inout_table_header">CheckIn/Out</th>
                <th class="room_details_table_header">Details</th>
                <th>Available</th>
            </tr>
        {% for room in patient_rooms %}
            <tr class="table_surgery_room">
                <td>{{room.room_number}}</td>
                {% if not room.is_occupied %}
                    <td>N/A</td>
                    <td>N/A</td>
                    <td><a href="{% url 'hospital:patient_check_in' room.id %}">Check patient in</a></td>
                    <td><a href="{% url 'hospital:rooms_patient_details' room.id %}">Details</a></td>
                    <td class="table_row_available"></td>
                {% else %}
                    <td>{{room.patient.lastName}}, {{room.patient.firstName}}</td>
                    <td>{{room.nurse.lastName}}, {{room.nurse.firstName}}</td>
                    <td><a href="{% url 'hospital:patient_check_out' room.id %}">Check patient out</a></td>
                    <td><a href="{% url 'hospital:rooms_patient_details' room.id %}">Details</a></td>
                    <td class="table_row_not_available"></td>
                {% endif %}
            </tr>
        {% endfor %}
        </table>
{% endblock %}

hospital_management_system/hospital/templates/hospital/room_details.html
{% extends "hospital/base.html" %}

{% block content %}
    <h2>Room Details</h2>
    <p>Room Number: {{ room.room_number }}</p>
    {% if not room.price is None %}
        <p>Price: {{ room.price }}</p>
    {% endif %}
{% endblock %}

hospital_management_system/hospital/templates/hospital/surgery_schedule.html
{% extends "hospital/base.html" %}

{% block header %}
    <div class="container_header">
        {% if hospital is not None %}
            <div class="container_hospital_info">
                <div class="hospital_title"><a class="hospital_title_text" href="{% url 'hospital:home' %}">{{ hospital.name }}</a></div>
                <div class="hospital_info">
                    <div>{{ hospital.address }}</div>
                    <div class="padding"></div>
                    <div>{{ hospital.phone_number }}</div>
                </div>
            </div>
        {% else %}
            <a href="/" class="logo">My Hospital</a>
        {% endif %}

        <div class="container_user_info">
            {% if user.is_authenticated %}
                <div class="user_name_info">Hello, {{user.username}}</div>
                <div><a class="log_out" href="{% url 'accounts:logout' %}">Log out</a></div>
            {% else %}
                <a href="{% url 'accounts:login' %}">Log in</a>
            {% endif %}
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="contianer_upcoming_surgeries">
            <h2 class="title_surgery_schedule">Upcoming Surgeries</h2>
            <table>
                <tr>
                    <th class="room_number_table_header">Room Number</th>
                    <th class="patient_name_table_header">Doctor</th>
                    <th>Patient</th>
                    <th class="room_details_table_header">Details</th>
                    <th class="surgery_details_status_header">Status</th>
                </tr>
            {% for sr in booked%}
                <tr class="table_row_surgery">
                    <td> {{ sr.room_number }}</td>
                    <td>{{sr.surgery.doctor_incharge.lastName}}, {{sr.surgery.doctor_incharge.firstName}}</td>
                    <td>{{sr.surgery.patient.lastName}}, {{sr.surgery.patient.firstName}}</td>
                    <td><a href="{% url 'Surgery_Details:Surgery' sr.id %}">Click for details</a> </td>
                {% if sr.surgery.start_time >= time %}
                    <td class="row_surgery_status_on_going">On Going</td>
                {% else %}
                    <td class="row_surgery_status_starting_soon">Starting Soon</td>
                {% endif %}
                </tr>
            {% endfor %}
            </table>
    </div>

    <div class="container_upcoming_surgeries">
            <h2 class="title_surgery_schedule">Free Surgery Rooms</h2>
            <table>
                <tr>
                    <th>Room Number</th>
                    <th>Details</th>
                    <th>Book</th>
                </tr>
            {% for sr in free%}
                <tr class="table_row_surgery">
                    <td>{{sr.room_number}}</td>
                    <td><a href="{% url 'hospital:rooms_surgery_details' sr.id %}">Details</a> </td>
                    <td><a href="{% url 'hospital:book_surgery' sr.id %}">Book</a></td>
                </tr>
            {% endfor %}
            </table>
    </div>
{% endblock %}